email: ozavala@coaps.fsu.edu

baseurl: "/particleviz/"
url: "https://olmozavala.github.io/"

# Build settings
plugins:
  - jekyll-feed

include:
  - ../README.md

defaults:
  - scope:
      path: ""
    values:
      layout: default

# ---------- General
description: "Visualizing Lagrangian model outputs the easy way."
title: ParticleViz

repository: olmozavala/particleviz
github:
  repository_url: https://github.com/olmozavala/particleviz

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
